/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanTestInstanceInstanceMatching.java
 *
 * Created on 24-oct-2011, 23:17:44
 */

package TestMatching.AutomaticTest.GUIs;

import DatabaseMathExpressions.DBFuntions;
import DatabaseMathExpressions.UserExpression;
import Matching.ExpressionMatching;
import Matching.Matching;
import MathExpression.Data.DMathExpression;
import MathExpression.Graphics.GMathExpression;

/**
 *
 * @author frank
 */
public class PanTestInstanceInstanceMatching extends javax.swing.JPanel {
    private final Matching matching;
    private final DBFuntions dbFunctions;

    private DMathExpression modelExpression;
    private DMathExpression instanceExpression;

    /** Creates new form PanTestInstanceInstanceMatching */
    public PanTestInstanceInstanceMatching() {
        initComponents();
        matching=new ExpressionMatching();
        dbFunctions=new DBFuntions();
        dbFunctions.openConnection();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alpha = new javax.swing.JTextField();
        beta = new javax.swing.JTextField();
        gama = new javax.swing.JTextField();
        isDelaunay = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botMatch = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        instance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panMatching1 = new GUIs.Matching.PanMatching();

        setLayout(new java.awt.BorderLayout());

        beta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaActionPerformed(evt);
            }
        });

        isDelaunay.setText("Delaunay");

        jLabel1.setText("Alpha :");

        jLabel2.setText("Beta : ");

        jLabel3.setText("Gama :");

        botMatch.setText("Match");
        botMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMatchActionPerformed(evt);
            }
        });

        jLabel4.setText("Model: ");

        jLabel5.setText("Instance");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(alpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(beta)))
                .add(67, 67, 67)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(gama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(137, 137, 137)
                        .add(botMatch))
                    .add(isDelaunay))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 107, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel4)
                    .add(jLabel5))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(instance)
                    .add(model, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(alpha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(gama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(botMatch)
                    .add(model, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel2)
                                .add(beta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(isDelaunay)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(instance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panMatching1.setPreferredSize(new java.awt.Dimension(1200, 1200));

        org.jdesktop.layout.GroupLayout panMatching1Layout = new org.jdesktop.layout.GroupLayout(panMatching1);
        panMatching1.setLayout(panMatching1Layout);
        panMatching1Layout.setHorizontalGroup(
            panMatching1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1200, Short.MAX_VALUE)
        );
        panMatching1Layout.setVerticalGroup(
            panMatching1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1200, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panMatching1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void betaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_betaActionPerformed

    private void botMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMatchActionPerformed
        // TODO add your handling code here:
        readExpressions();
        String[][] strMatch=matching.match(modelExpression,instanceExpression);
        int[][] match=Util.Util.stringToIntMatrix(strMatch);
        panMatching1.setgMathExpressionModel((GMathExpression) modelExpression);
        panMatching1.setgMathExpressionInput((GMathExpression) instanceExpression);
        panMatching1.setMatch(match);
        panMatching1.setUpMatchingDrawer();
        panMatching1.repaint();
    }//GEN-LAST:event_botMatchActionPerformed


   private void readExpressions(){
       String idModel=model.getText();
       String idInstance=instance.getText();
       this.modelExpression = (dbFunctions.getUserExpressionByID(Integer.valueOf(idModel))).getdMExpression();
       this.instanceExpression = (dbFunctions.getUserExpressionByID(Integer.valueOf(idInstance))).getdMExpression();
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alpha;
    private javax.swing.JTextField beta;
    private javax.swing.JButton botMatch;
    private javax.swing.JTextField gama;
    private javax.swing.JTextField instance;
    private javax.swing.JCheckBox isDelaunay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model;
    private GUIs.Matching.PanMatching panMatching1;
    // End of variables declaration//GEN-END:variables

}
