/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramAdministratorMainFrame.java
 *
 * Created on 19-ago-2011, 23:29:19
 */

package GUIs.WellComeToSystem;

import DatabaseMathExpressions.DBFuntions;
import GUIs.InputOfExpressions.panConfigurateWritting;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JFrame;

/**
 *
 * @author frank
 */
public class FramAdministratorMainFrame extends javax.swing.JFrame {

    /** Creates new form FramAdministratorMainFrame */
    public FramAdministratorMainFrame(DBFuntions databaseFunctions,String usersName) {
        initComponents();
        administratorMainPanel1.setUpDBFunctionsAndUser(databaseFunctions,usersName);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        administratorMainPanel1 = new GUIs.AdministratorMainPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(administratorMainPanel1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Writing configuration");

        jMenuItem1.setText("Time and writing area");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:  
}//GEN-LAST:event_jMenuItem1MousePressed

private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1MouseClicked

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        panConfigurateWritting panConfigure=new panConfigurateWritting();
        panConfigure.addWritingPanel(this.administratorMainPanel1.getWritingPanelUserExpressions());
        panConfigure.addWritingPanel(this.administratorMainPanel1.getwritingPanelModels());
        panConfigure.setUpSliders();
        JFrame frame=new JFrame();
        frame.setContentPane(panConfigure);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FramAdministratorMainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIs.AdministratorMainPanel administratorMainPanel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
